os:
  - linux
language: php
php:
  - '7.2'
before_script:
  - rm -rf vendor
  - composer self-update
  - composer install --no-interaction
  - cp .env.testing .env
  - nvm install node
  - npm install npm@latest -g
  - npm install
  - php artisan migrate --seed --env=testing
script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit