services:
    app:
        build:
            context: ./vendor/postboxcms/desk/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: desk-8.3/app
        container_name: Postbox
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            POSTBOXCMS_DESK: 1
            XDEBUG_MODE: '${DESK_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${DESK_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - desk
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: MySQL
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'desk-mysql:/var/lib/mysql'
            - './vendor/postboxcms/desk/database/mysql/create-postbox-database.sh:/docker-entrypoint-initdb.d/10-create-postbox-database.sh'
        networks:
            - desk
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: Redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - desk
networks:
    desk:
        driver: bridge
        name: postbox
volumes:
    desk-mysql:
        driver: local
        name: DeskStorage
