[Unit]
Description=PostboxCMS SSR Server
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory={{DOCUMENT_ROOT}}
ExecStart=/usr/bin/pm2 start server --name ssr --env production
ExecStop=/usr/bin/pm2 stop ssr
Restart=always
Environment=NODE_ENV=production
StartLimitIntervalSec=0
StartLimitBurst=100
RestartSec=5

[Install]
WantedBy=multi-user.target
